# NB: Always use immutable tags (e.g. not latest etc) on docker refs.
# Any :latest tags on this file will be replaced with athens release version on release.

version: "3.4"
services:
  athens:
    image: ghcr.io/athensresearch/athens:latest
    # Uncomment the build sections if you want docker compose to build them locally.
    # build:
    #   context: .
    #   dockerfile: athens.dockerfile
    restart: always
    depends_on:
      fluree:
        condition: service_healthy
    ports:
      - 3010:3010 # Change this according to config.edn
    volumes:
      - ./athens-data/logs:/srv/athens/logs
    environment:
      # Use system env vars for settings if available.
      # config_edn is deep merged with the whole config file
      - CONFIG_EDN=${CONFIG_EDN:-{:fluree {:servers ["http://fluree:8090"]}}}
    healthcheck:
      test: curl -f localhost:3010/health-check
      interval: 5s
      timeout: 60s
      retries: 3
      start_period: 5s


  nginx:
    image: ghcr.io/athensresearch/nginx:latest
    # build:
    #  context: .
    #  dockerfile: nginx.dockerfile
    restart: always
    depends_on:
      athens:
        condition: service_healthy
    restart: always
    ports:
      - 80:80

  fluree:
    # Under default settings maximum recommended event size is 2mb.
    # Can be increased via fdb-memory-reindex-max to up to 10mb.
    image: fluree/ledger:sha-70719dcb
    restart: always
    ports:
      - 8090:8090
    volumes:
      - ./athens-data/fluree:/var/lib/fluree
    healthcheck:
      test: curl -f localhost:8090/fdb/health
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 5s
