version: "3"
services:
  athens:
    image: ghcr.io/athensresearch/athens:latest
    # Uncomment the build sections if you want docker compose to build them locally.
    # build:
    #  context: .
    #  dockerfile: athens.dockerfile
    restart: always
    depends_on:
      - fluree
    expose:
      - 3010 # Change this according to config.edn
    volumes:
      - ./athens-data/logs:/srv/athens/logs
    environment:
      # Use system env vars for settings if available.
      # config_edn is deep merged with the whole config file
      - CONFIG_EDN=${CONFIG_EDN:-{}}


  nginx:
    image: ghcr.io/athensresearch/nginx:latest
    # build:
    #  context: .
    #  dockerfile: nginx.dockerfile
    restart: always
    depends_on:
      - athens
    restart: always
    ports:
      - 80:80

  fluree:
    # Under default settings maximum recommended event size is 2mb.
    # Can be increased via fdb-memory-reindex-max to up to 10mb.
    image: fluree/ledger:latest
    restart: always
    ports:
      - 8090:8090
    volumes:
      - ./athens-data/fluree:/var/lib/fluree
