name: 'Clojure Env'
description: 'Setup a clojure environment'
runs:
  using: "composite"
  steps:
    - name: Restore maven
      uses: actions/cache@v2
      id: restore-maven
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - uses: DeLaGuardo/setup-clojure@3.5
      with:
        cli: 1.10.3.986
        lein: 2.9.7

    - name: Fetch maven dependencies
      shell: bash
      # 'if' not supported yet, workaround in bash
      # https://github.com/actions/runner/issues/834
      # if: steps.restore-maven.outputs.cache-hit != 'true'
      # run: lein deps
      run: |
        if echo ${{ steps.restore-maven.outputs.cache-hit }} | grep -c "true"
        then
          echo "Cache hit - skipping dependency installation"
        else
          ${{ runner.os != 'Windows' && 'lein deps' || 'pwsh -c "lein deps"' }}
        fi

     
